### ISSUE TITLE
To-do for SplitPy

### ISSUE THREAD

**Issue by paudetseis** [paudetseis/SplitPy#2]
- [x] Implement Continuous Integration using Travis
- [x] Deploy documentation using Travis in gh-pages branch
- [ ] Write tests for code coverage
- [ ] Write better examples for code usage outside of scripts

**Comment by juch427** [comment]
Hi,
 I am trying to use [SplitPy](https://github.com/paudetseis/SplitPy) to do teleseismic shear-wave splitting analysis and found it very useful. I also apply [OrientPy](https://github.com/nfsi-canada/OrientPy) to measure the misalignment for each station. So I wonder if you can possibly add one module/class to correct the misorientation in your software.
Thanks
Changhui

**Comment by paudetseis** [comment]
Hi,
If you are using `Z12` channels for data on FDSN archives, the data will be rotated using the `azcorr` field in the `StDb` database. In this case, the workflow is to run `OrientPy`, then edit the `StDb` database using the `edit_stdb` script (or manually change the `azcorr` field in the .csv file, and then run the `SplitPy` scripts normally. 

If you found a misalignment in `ZNE` data sets, then `SplitPy` will not use the `azcorr` field to further rotate the channels. Admittedly, this is a limitation.

Please provide more details of your situation and I can help adapt the code accordingly.

**Comment by juch427** [comment]
Hi,
Thanks for your reply. 
What I hope is to use the `azcorr` field for `ZNE` data sets since the misalignment when installing the seismograph. Though it cannot be implemented right now in the codes, I believe it is an important part when doing shear wave splitting analysis. Anyway, thanks for sharing your codes, and hoping to see the update.
Changhui
